:bug: Uncaught TypeError: EJSON.inflate is not a function
my bad.  mongodb-js/extended-json#24 should have been a major version
bump to 2.x.

This patch adds aliases for EJSON.deflate/inflate to print deprecation
warnings and properly forward to deserialize/serialize.

HT @ksuarz